import mongoose from "mongoose";

const ihracatSchema = new mongoose.Schema(
  {
    birinci_alt_rejim_aciklamasi: { type: String, required: false },
    ticari_tanimi_31: { type: String, required: false },
    alici_adi: { type: String, required: false },
    alici_kimlik_no: { type: String, required: false },
    belge_no: { type: String, required: false },
    fatura_tutari: { type: Number, required: false },
    gtip_aciklamasi: { type: String, required: false },
    gtip_kodu: { type: String, required: false },
    gonderen_adi: { type: String, required: false },
    gonderici_alici_adi: { type: String, required: false },
    gonderici_alici_vergi_no: { type: String, required: false },
    gonderici_kimlik_no: { type: String, required: false },
    gumruk_istatistik_tarihi_bordro_tarihi: { type: Date, required: false },
    hesaplanmis_kalem_kiymeti_usd_degeri: { type: Number, required: false },
    kalem_rejim_kodu: { type: String, required: false },
    kalem_sira_no: { type: Number, required: false },
    kap_adedi: { type: Number, required: false },
    mense_ulke_kodu: { type: String, required: false },
    navlun_tutari_tl_degeri: { type: Number, required: false },
    net_agirlik: { type: Number, required: false },
    sigorta_tutari: { type: Number, required: false },
    sinirdaki_aracin_tasima_sekli_kodu: { type: String, required: false },
    tcgb_kapanis_tarihi: { type: Date, required: false },
    tcgb_tescil_no: { type: String, required: false },
    teslim_sekli_kodu: { type: String, required: false },
    ticaret_yapilan_ulke_kodu: { type: String, required: false },
    varis_ulkesi_adi: { type: String, required: false },
    yukleme_bosaltma_yapilan_gumruk_idaresi_kodu: {
      type: String,
      required: false,
    },
    cikis_ulkesi_kodu: { type: String, required: false },
    ulke_kodu: { type: String, required: false },
    ulke_tanim: { type: String, required: false },
    istatistiki_birim_kodu: { type: String, required: false },
    beyan_sahibi_adi_unvani: { type: String, required: false },
    beyan_sahibi_kimlik_no: { type: String, required: false },
    brut_agirlik: { type: Number, required: false },
    doviz_turu_aciklamasi: { type: String, required: false },
    fatura_doviz_kodu: { type: String, required: false },
    gtip_tanimi: { type: String, required: false },
    gidecegi_ulke_17_kodu: { type: String, required: false },
    gumruk_idaresi_kodu: { type: String, required: false },
    havale_hatti: { type: String, required: false },
    hesaplanmis_istatistiki_kiymet: { type: Number, required: false },
    kullanici_birim_kiymeti_usd_degeri: { type: Number, required: false },
    muayene_hatti: { type: String, required: false },
    rejim_kodu: { type: String, required: false },
    satisa_esas_miktar: { type: Number, required: false },
    satisa_esas_miktar_olcu_birimi_kodu: { type: String, required: false },
    tcgb_bolge_mudurlugu_kodu: { type: String, required: false },
    tcgb_statu_aciklamasi: { type: String, required: false },
    tcgb_basmudurluk_kodu: { type: String, required: false },
    ticari_odeme_sekli_tanim: { type: String, required: false },
    toplam_kap_adedi: { type: Number, required: false },
    cikistaki_aracin_kayitli_oldugu_ulke_kodu: {
      type: String,
      required: false,
    },
    olcu_birimi_aciklamasi: { type: String, required: false },
    olcu_esya_miktari: { type: Number, required: false },
    istatistiki_kiymet: { type: Number, required: false },
    istatistiki_kiymet_usd_degeri: { type: Number, required: false },
    istatistiki_miktar: { type: Number, required: false },
    gumruk_ve_ticaret_bolge_mudurlugu: { type: String, required: false },
  },
  {
    strict: false,
    timestamps: true,
  },
  "ihracat"
);

const Ihracat = mongoose.model("Ihracat", ihracatSchema, "ihracat");

export default Ihracat;
